# DevOps Pipeline Configuration
pipeline:
  name: "Universal DevOps Pipeline"
  version: "1.0.0"
  
# Supported application types
app_types:
  - java-spring-boot
  - react-frontend
  - node-backend
  - python-django

# Default configurations
defaults:
  aws_region: "us-east-1"
  instance_type: "t3.medium"
  min_instances: 2
  max_instances: 6
  health_check_path: "/health"
  enable_database: false
  database_type: "postgres"
  database_instance_class: "db.t3.micro"
  
# Environment configurations
environments:
  staging:
    instance_count: 2
    instance_type: "t3.small"
  production:
    instance_count: 3
    instance_type: "t3.medium"