name: Deploy Frontend Application

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      app_type:
        required: true
        type: string
        default: 'react-frontend'
      environment:
        required: true
        type: string
        default: 'staging'
      aws_region:
        required: false
        type: string
        default: 'us-east-1'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      EC2_SSH_KEY:
        required: true

jobs:
  setup-infrastructure:
    if: ${{ inputs.environment == 'staging' }}
    uses: ./.github/workflows/setup-infrastructure.yml
    with:
      project_name: ${{ inputs.project_name }}
      app_type: ${{ inputs.app_type }}
      aws_region: ${{ inputs.aws_region }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
  deploy:
    needs: [setup-infrastructure]
    if: always() && (needs.setup-infrastructure.result == 'success' || needs.setup-infrastructure.result == 'skipped')
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
          
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ inputs.project_name }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ inputs.project_name }}:$IMAGE_TAG
          
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Install Ansible
        run: |
          pip install ansible boto3
          
      - name: Deploy to EC2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ansible-playbook -i inventory/${{ inputs.environment }} \
            deploy.yml \
            -e project_name=${{ inputs.project_name }} \
            -e app_type=${{ inputs.app_type }} \
            -e image_tag=$IMAGE_TAG \
            -e environment=${{ inputs.environment }} \
            -e aws_region=${{ inputs.aws_region }}